fieldenms/tg

- platform-web-resources/src/main/java/ua/com/fielden/platform/web/test/server/WebUiConfig.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-entity-grid-inspector-template.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/spikes/scroll-spike.html
> Issue #774

- platform-dao/src/main/java/ua/com/fielden/platform/eql/meta/MetadataGenerator.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/AbstractEntity.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/reflection/Finder.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/utils/EntityUtils.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/entity/AbstractEntityTest.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/entity/Entity.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/reflection/FinderTest.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/utils/EntityUtilsTest.java
> Issue #787

- platform-dao/src/main/java/ua/com/fielden/platform/entity/query/EntityContainer.java
- platform-dao/src/test/java/ua/com/fielden/platform/entity/query/fetching/EntityQueryExecutionTest.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/reflection/tg-reflector.html
> Issue #795

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/menu/MenuProducer.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/MenuWebUiConfig.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/test/server/PopulateDb.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/test/server/WebUiConfig.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/test/server/config/StandardActions.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/dom/DomElement.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/app/AbstractWebUiConfig.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/menu/IModuleConfig.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/menu/impl/MainMenuBuilder.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/menu/impl/WebMainMenu.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/menu/module/IModuleConfigWithAction.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/menu/module/impl/ModuleConfig.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/menu/module/impl/WebMenuModule.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/view/master/api/compound/impl/CompoundMasterBuilder.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/actions/tg-ui-action.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/app/tg-desktop-app.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/views/tg-app-menu.html
> Issue #803

- platform-web-resources/src/main/java/ua/com/fielden/platform/web/test/server/PopulateDb.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/reflection/test/tg-reflector.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/reflection/tg-reflector.html
> Issue #804

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-entity-editor.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/views/tg-app-menu.html
> Issue #808

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/test/tg-datetime-picker-value-approximations-for-24hours-for-persisted-entity.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/test/tg-datetime-picker-value-approximations-for-24hours.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-datetime-picker.html
> Issue #810

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/criterion/tg-abstract-criterion-behavior.html
> Issue #813

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre-behavior.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-entity-grid-inspector-template.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/test/tg-entity-master.html
> Issue #812

- platform-dao/src/main/java/ua/com/fielden/platform/entity/EntityResourceContinuationsHelper.java
> Issue #820

- platform-dao/src/test/java/ua/com/fielden/platform/dao/dynamic/DynamicQueryBuilderSqlTest.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/query/fluent/EntityQueryUtils.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity_centre/review/DynamicQueryBuilder.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/reflection/PropertyTypeDeterminator.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/utils/MiscUtilities.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/reflection/PropertyTypeDeterminatorCheckingEnhancementsTest.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/reflection/asm/impl/DynamicEntityTypeMixedAndRepetitiveModificationTest.java
> Issue #823

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-decimal-editor.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-integer-editor.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-money-editor.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/reflection/tg-numeric-utils.html
> Issue #826

- platform-dao/src/test/java/ua/com/fielden/platform/migration/UserPasswordResetTest.java
- platform-dao/src/test/java/ua/com/fielden/platform/user/UserTestCase.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/security/user/User.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/security/user/definers/UserBaseDefiner.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/security/user/definers/UserBasedOnUserDefiner.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/security/user/validators/UserBaseOnUserValidator.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/security/user/validators/UserBaseValidator.java
> Issue #829

- platform-web-resources/src/main/java/ua/com/fielden/platform/web/test/server/WebUiConfig.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/test/server/config/StandardActions.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/action/CentreConfigurationWebUiConfig.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/action/exceptions/ActionConfigurationException.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/action/pre/SequentialEditPreAction.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-custom-action-dialog.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/actions/tg-entity-master-closing-behavior.html
> Issue #793

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/file_reports/WorkbookExporter.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/file_reports/WorkbookExporterTest.java
> Issue #838

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/ioc/ObservableMutatorInterceptor.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/meta/MetaProperty.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/meta/MetaPropertyFull.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/entity/meta/PropertyDependencyHandlingTest.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/entity/meta/test_entities/EntityWithDependentProperties.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/entity/meta/test_entities/validators/EntityWithDependentPropertiesFive.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/entity/meta/test_entities/validators/EntityWithDependentPropertiesFour.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/entity/meta/test_entities/validators/EntityWithDependentPropertiesOne.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/entity/meta/test_entities/validators/EntityWithDependentPropertiesThree.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/entity/meta/test_entities/validators/EntityWithDependentPropertiesTwo.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/utils/EntityResourceUtils.java
> Issue #778

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/serialisation/jackson/DefaultValueContract.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/serialisation/jackson/EntitySerialiser.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/serialisation/jackson/EntityTypeProp.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-decimal-editor.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-money-editor.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-entity-grid-inspector.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/reflection/test/tg-reflector.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/reflection/tg-reflector.html
> Issue #322

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-entity-editor-result.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-entity-editor.html
> Issue #858

- platform-dao/src/test/java/ua/com/fielden/platform/dao/dynamic/DynamicQueryBuilderSqlTest.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/basic/autocompleter/PojoValueMatcher.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity_centre/review/DynamicParamBuilder.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity_centre/review/DynamicQueryBuilder.java
> Issue #857

- platform-dao/src/main/java/ua/com/fielden/platform/entity/query/generation/EntQueryBlocks.java
- platform-dao/src/main/java/ua/com/fielden/platform/entity/query/generation/EntQueryGenerator.java
- platform-dao/src/main/java/ua/com/fielden/platform/entity/query/generation/elements/EntQuery.java
- platform-dao/src/test/java/ua/com/fielden/platform/entity/query/QueryModelCompositionTest.java
- platform-dao/src/test/java/ua/com/fielden/platform/entity/query/generation/BaseEntQueryTCase.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/query/fluent/CompletedAndYielded.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/query/fluent/CompletedCommon.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/query/fluent/EntityQueryProgressiveInterfaces.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/query/fluent/FirstYieldedItemAlias.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/query/fluent/SubsequentCompletedAndYielded.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/query/fluent/Tokens.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/query/model/AggregatedResultQueryModel.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/query/model/EntityResultQueryModel.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/query/model/PrimitiveResultQueryModel.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/query/model/QueryModel.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/query/model/SingleResultQueryModel.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/entity/query/fluent/FluencyApiTest.java
> Issue #866

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-collectional-editor.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-collectional-representor.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-colour-picker.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-datetime-picker.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-decimal-editor.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-editor-behavior.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-entity-editor.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-hyperlink-editor.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-integer-editor.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-money-editor.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-multiline-text-editor.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-singleline-text-editor.html
> Issue #859

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/AbstractFunctionalEntityWithCentreContext.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/EntityEditAction.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/EntityEditActionProducer.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/EntityManipulationActionProducer.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/view/master/EntityMaster.java
> Issue #875

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-custom-action-dialog.html
> Issue #878

- platform-dao/src/main/java/ua/com/fielden/platform/dao/DomainMetadata.java
- platform-dao/src/main/java/ua/com/fielden/platform/entity/query/EntityRetrievalModel.java
- platform-dao/src/main/java/ua/com/fielden/platform/entity/query/generation/elements/EntQuery.java
- platform-dao/src/main/java/ua/com/fielden/platform/entity/query/generation/elements/Yields.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity_centre/exceptions/EntityCentreExecutionException.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity_centre/review/DynamicParamBuilder.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity_centre/review/DynamicQueryBuilder.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/utils/EntityUtils.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/utils/EntityUtilsTest.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/impl/SelectionCriteriaBuilderAsMulti.java
> Issue #881

- platform-dao/src/test/java/ua/com/fielden/platform/co_finder/CompanionFinderTest.java
- platform-dao/src/test/java/ua/com/fielden/platform/dao/CommonEntityDaoStreamingTestCase.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/companion/IEntityReader.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/dao/IEntityDao.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/factory/DefaultCompanionObjectFinderImpl.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/factory/ICompanionObjectFinder.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/meta/IAfterChangeEventHandler.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/meta/impl/AbstractAfterChangeEventHandler.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/meta/impl/AbstractBeforeChangeEventHandler.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/validation/IBeforeChangeEventHandler.java
> Issue #891

- platform-dao/src/main/java/ua/com/fielden/platform/dao/CommonEntityDao.java
- platform-dao/src/main/java/ua/com/fielden/platform/data/IDomainDrivenData.java
- platform-dao/src/main/java/ua/com/fielden/platform/devdb_support/DomainDrivenDataPopulation.java
- platform-dao/src/main/java/ua/com/fielden/platform/test/AbstractDomainDrivenTestCase.java
- platform-dao/src/test/java/ua/com/fielden/platform/dao/CommonEntityDaoCompanionInstantiationTest.java
- platform-dao/src/test/java/ua/com/fielden/platform/dao/CommonEntityDaoInstrumentationTest.java
- platform-dao/src/test/java/ua/com/fielden/platform/entity/proxy/EntityProxyLoadingTest.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/companion/ICanReadUninstrumented.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/dao/DefaultEntityProducerWithContext.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/dao/IEntityDao.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/factory/DefaultCompanionObjectFinderImpl.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/factory/ICompanionObjectFinder.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/TgOrgUnit5.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/utils/EntityResourceUtils.java
> Issue #895

- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/EntityCentre.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre-behavior.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre-insertion-point.html
> Issue #897

- platform-dao/src/main/java/ua/com/fielden/platform/entity/query/generation/elements/AbstractSource.java
- platform-dao/src/main/java/ua/com/fielden/platform/entity/query/generation/elements/EntQuery.java
- platform-dao/src/main/java/ua/com/fielden/platform/entity/query/generation/elements/Yields.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity_centre/review/DynamicQueryBuilder.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/reflection/AnnotationReflector.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/reflection/AnnotationReflectorTest.java
> Issue #903

- platform-web-ui/src/main/java/ua/com/fielden/platform/web/action/CentreConfigurationWebUiConfig.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre-behavior.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/egi-dynamic-columns-example.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/test/tg-egi-dynamic-column-dom-test.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-entity-grid-inspector.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/tests.html
> Issue #906

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/actions/tg-focus-restoration-behavior.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/actions/tg-shortcut-processing-behavior.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-selection-view.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-editor-behavior.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-entity-grid-inspector.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/test/tg-entity-master.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/tg-entity-master-behavior.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/tg-entity-master-template-behavior.html
> Issue #910

- platform-dao/src/main/java/ua/com/fielden/platform/entity/query/EntityRetrievalModel.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/query/fluent/EntityQueryUtils.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/query/fluent/fetch.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity_centre/review/DynamicFetchBuilder.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/entity_centre/review/DynamicFetchBuilderTest.java
> Issue #919

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/test/tg-egi-dynamic-rendering-hints-test.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-entity-grid-inspector.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/tests.html
> Issue #921

- platform-dao/src/main/java/ua/com/fielden/platform/companion/helper/ActivatableEntityRetrospectionHelper.java
- platform-dao/src/test/java/ua/com/fielden/platform/entity/ActivatableEntitiesWithSkipeActivatableTrackingTest.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/annotation/SkipActivatableTracking.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/validation/EntityExistsValidator.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/TgSystem.java
> Issue #893

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity_centre/review/criteria/EntityQueryCriteria.java
> Issue #931

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/domaintree/impl/GlobalDomainTreeManager.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre-behavior.html
> Issue #929

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-entity-editor.html
> Issue #939

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/DefaultEntityProducerWithContext.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/IContextDecomposer.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/app/config/IWebUiBuilder.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/app/config/WebUiBuilder.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/app/exceptions/WebUiBuilderException.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/EntityCentre.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/EntityCentreConfig.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/impl/EntityCentreBuilder.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/impl/ResultSetBuilder.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/impl/TopLevelActionsBuilder.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/resultset/IResultSetBuilder5WithPropAction.java
- platform-web-ui/src/test/java/ua/com/fielden/platform/web/centre/api/impl/EntityCentreBuilderResultSetTest.java
> #950 Implemented the core issue requirements.

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/AbstractFunctionalEntityToOpenCompoundMaster.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/view/master/api/compound/impl/MasterWithMenu.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/menu/tg-master-menu.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/reflection/tg-reflector.html
> Issue #937

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/web/utils/EntityResourceUtils.java
Partial changes for #960 issue required for fieldenms/TTGAMS#604
> Issue #960 partial changes

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/actions/tg-ui-action.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-custom-action-dialog.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-entity-grid-inspector.html
> Issue #962

- platform-dao/src/main/java/ua/com/fielden/platform/sample/domain/TgEntityWithPropertyDependencyDao.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/EntityNewAction.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/TgEntityWithPropertyDependency.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/TgEntityWithPropertyDependencyProducer.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/definers/TgEntityWithPropertyDependencyProp1Definer.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/definers/TgEntityWithPropertyDependencyPropXAndPropYDefiner.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/ui/menu/sample/MiTgEntityWithPropertyDependency.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/web/utils/EntityResourceUtils.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/test/server/WebUiConfig.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/binding/tg-entity-binder-behavior.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/test/tg-entity-master-editors-touching.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/tg-entity-master-behavior.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/reflection/tg-reflector.html
> Issue #960

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre-behavior.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre.html
> Issue #966

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/web/utils/EntityResourceUtils.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/factories/webui/EntityAutocompletionResourceFactory.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/CriteriaEntityAutocompletionResource.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/EntityAutocompletionResource.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/EntityCentre.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/EntityCentreConfig.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/impl/EntityCentreBuilder.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/impl/SelectionCriteriaBuilderAsMulti.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/impl/TopLevelActionsBuilder.java
- platform-web-ui/src/test/java/ua/com/fielden/platform/web/centre/api/impl/EntityCentreBuilderSelectionCritTest.java
> Issue #969

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-centre-result-view.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre-insertion-point.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre-template.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre.html
> Issue #977

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/tg-entity-master-behavior.html
> Issue #980

- platform-dao/src/main/java/ua/com/fielden/platform/entity/EntityResourceContinuationsHelper.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/web/utils/EntityResourceUtils.java
> Issue #946

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/tg-entity-master-behavior.html
> Issue #983

- platform-dao/src/main/java/ua/com/fielden/platform/companion/PersistentEntitySaver.java
- platform-dao/src/main/java/ua/com/fielden/platform/dao/CommonEntityDao.java
- platform-dao/src/test/java/ua/com/fielden/platform/dao/CommonEntityDaoQuckSaveTest.java
- platform-dao/src/test/java/ua/com/fielden/platform/dao/CommonEntityDaoTest.java
- platform-dao/src/test/java/ua/com/fielden/platform/persistence/types/EntityWithMoney.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/AbstractEntity.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/meta/MetaProperty.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/meta/MetaPropertyFull.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/validation/custom/DefaultEntityValidator.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/reflection/Reflector.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/reflection/ReflectorTest.java
> Issue #987

- platform-dao/src/main/java/ua/com/fielden/platform/dao/CommonEntityDao.java
- platform-dao/src/main/java/ua/com/fielden/platform/dao/EntityAggregatesDao.java
- platform-dao/src/main/java/ua/com/fielden/platform/dao/GeneratedEntityDao.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/companion/IEntityReader.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/dao/IComputationMonitor.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/AbstractEntity.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/factory/DefaultCompanionObjectFinderImpl.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/factory/ICompanionObjectFinder.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/ioc/ObservableMutatorInterceptor.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/reflection/CompanionObjectAutobinder.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/crit_gen/CriteriaGeneratorTestModule.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/crit_gen/GeneratedEntityControllerStub.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/crit_gen/LastLevelEntityDaoStub.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/crit_gen/SecondLevelEntityDaoStub.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/crit_gen/TgSystemDaoStub.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/crit_gen/TopLevelEntityDaoStub.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/test/CommonTestEntityModuleWithPropertyFactory.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/utils/CollectionUtil.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/utils/StreamUtils.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/utils/StreamUtilsTest.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/test/server/TgTestApplicationServerModule.java
This PR includes various improvements of a general nature.
> Issue tg air #636

- platform-dao/src/main/java/ua/com/fielden/platform/entity/query/generation/AbstractTokensBuilder.java
- platform-dao/src/main/java/ua/com/fielden/platform/entity/query/generation/AddDateIntervalBuilder.java
- platform-dao/src/main/java/ua/com/fielden/platform/entity/query/generation/elements/AddDateInterval.java
- platform-dao/src/test/java/ua/com/fielden/platform/entity/query/fetching/EntityQueryExecutionTest.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/query/fluent/DateAddIntervalFunctionArgument.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/query/fluent/DateAddIntervalFunctionTo.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/query/fluent/DateAddIntervalUnit.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/query/fluent/EntityQueryProgressiveInterfaces.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/query/fluent/SingleOperand.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/query/fluent/Tokens.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/query/fluent/enums/Functions.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/entity/query/fluent/FluencyApiTest.java
> Issue #996

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/basic/autocompleter/AbstractSearchEntityByKeyWithCentreContext.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/basic/autocompleter/AbstractSearchEntityByKeyWithContext.java
> #1003 Default value matchers: developer productivity

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre-template-behavior.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-confirmation-dialog.html
> Issue #1017

- platform-web-ui/src/main/java/ua/com/fielden/platform/web/view/master/chart/decker/api/impl/ChartDeckerMaster.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/chart-decker/tg-chart-decker-template-behavior.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-bar-chart/d3-bar-chart.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-bar-chart/tg-bar-chart.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/reflection/tg-polymer-utils.html
> Issue #1031

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-entity-editor-result.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-entity-editor.html
> Issue #1041

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-month-selector.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-datetime-picker.html
> Issue #1077

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/menu/tg-master-menu.html
> Issue #1076

- platform-web-resources/src/main/java/ua/com/fielden/platform/web/test/server/WebUiConfig.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/layout/api/IFlex.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/layout/api/impl/LayoutCellBuilder.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/view/master/api/widgets/impl/MultilineTextConfig.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/view/master/api/widgets/multilinetext/IMultilineTextConfig0.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/view/master/api/widgets/multilinetext/IMultilineTextConfigWithRowNumber.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/view/master/api/widgets/multilinetext/impl/MultilineTextWidget.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-multiline-text-editor.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/views/tg-app-menu.html
> Issue #1071

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-boolean-editor.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-editor.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-entity-editor.html
> Issue #1025

- platform-dao/src/main/java/ua/com/fielden/platform/attachment/AttachmentDao.java
- platform-dao/src/main/java/ua/com/fielden/platform/attachment/AttachmentUtils.java
- platform-dao/src/main/java/ua/com/fielden/platform/sample/domain/TgPersistentEntityWithPropertiesDao.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/attachment/Attachment.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/attachment/IAttachment.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/attachment/definers/AssignAttachmentTitle.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/attachment/matcher/AbstractAttachmentForMasterMatcher.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/types/Hyperlink.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/web/utils/EntityResourceUtils.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/binding/tg-entity-binder-behavior.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-hyperlink-editor.html
> Issue #1083

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-datetime-picker.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-custom-action-dialog.html
> Issue #1085

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-datetime-picker.html
> Issue #1114

- platform-dao/pom.xml
- platform-dao/src/main/java/ua/com/fielden/platform/attachment/AttachmentUploaderDao.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/AttachmentDownloadResource.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/FileProcessingResource.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/test/server/WebUiResources.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/binding/tg-entity-binder-behavior.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/file_operations/tg-file-processing-behavior.html
> Issue #1128

- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/CentreResource.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/CentreResourceUtils.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/CriteriaResource.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/action/CentreConfigurationWebUiConfig.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/action/post/GuardCentreRegenerationPostAction.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/test/tg-entity-centre-generation.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre-behavior.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-selection-criteria-behavior.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/views/tg-menu-item-view.html
> Issue #1094

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre-behavior.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-editor-behavior.html
> Issue #1146

- platform-dao/src/main/java/ua/com/fielden/platform/attachment/AttachmentsUploadActionDao.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/attachment/producers/AttachmentsUploadActionProducer.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/context/IEntityCentreContextSelectorFunction.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/view/master/attachments/AttachmentsUploadActionMaster.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/file_operations/tg-attachment-uploader-list.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/tg-entity-master-template.html
> Issue #1138

- platform-dao/src/main/java/ua/com/fielden/platform/web/centre/CentreConfigUpdaterDao.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/CollectionModificationUtils.java
> Issue #1148

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-decimal-editor.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-integer-editor.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-money-editor.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/reflection/test/tg-numeric-utils.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/reflection/tg-numeric-utils.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/tests.html
> Issue #1154

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-calendar.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-month-selector.html
> Issue #1162

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-calendar.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-month-selector.html
> Issue #1161

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/test/tg-datetime-picker-time-zones-for-24hours-for-persisted-entity.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-datetime-picker.html
> Issue #1166

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-tooltip-behavior.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-tooltip.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-boolean-editor.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-colour-picker.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-datetime-picker.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-decimal-editor.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-editor.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-entity-editor.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-hyperlink-editor.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-integer-editor.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-money-editor.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-multiline-text-editor.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-singleline-text-editor.html
> Issue #1174

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-tree.html
> Issue #1168

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-collectional-representor.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-entity-grid-inspector.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/reflection/tg-polymer-utils.html
> Issue #1189

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/binding/tg-entity-binder-behavior.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre-template-behavior.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/reflection/test/tg-numeric-utils.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/reflection/tg-numeric-utils.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/sse/tg-sse-behavior.html
> Issue #1192

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/binding/tg-entity-binder-behavior.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-custom-action-dialog.html
> Issue #1211

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-selection-view.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-focus-traversal-behavior.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-editor-behavior.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/tg-entity-master-behavior.html
> Issue #1173

- platform-dao/src/test/java/ua/com/fielden/platform/dao/dynamic/DynamicQueryBuilderSqlTest.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity_centre/review/DynamicQueryBuilder.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/entity_centre/review/ChartAnalysisQueryGenerationTest.java
> Issue #1198

- platform-dao/src/test/java/ua/com/fielden/platform/entity/matcher/DaoValueMatcherFactoryTest.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/attachment/matcher/AbstractAttachmentForMasterMatcher.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/basic/IValueMatcherWithFetch.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/basic/autocompleter/AbstractSearchEntityByKeyWithCentreContext.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/basic/autocompleter/AbstractSearchEntityByKeyWithContext.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/basic/autocompleter/EntityQueryValueMatcher.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/CriteriaEntityAutocompletionResource.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/EntityAutocompletionResource.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/test/server/WebUiConfig.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-scrollable-component.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-entity-editor-result.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-entity-editor.html
> Issue #543

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/tg-entity-master-template-behavior.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/tg-entity-master.html
> Issue #1224

- platform-dao/src/main/java/ua/com/fielden/platform/entity/query/generation/elements/Conditions.java
- platform-dao/src/main/java/ua/com/fielden/platform/entity/query/generation/elements/EntQuery.java
- platform-dao/src/test/java/ua/com/fielden/platform/entity/query/QueryShortcutsTest.java
- platform-dao/src/test/java/ua/com/fielden/platform/entity/query/generation/BaseEntQueryTCase.java
> Issue #1221

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre-behavior.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/tg-entity-master-behavior.html
> Issue #1227

- platform-dao/src/main/java/ua/com/fielden/platform/web/centre/CentreConfigUpdaterDao.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/web/centre/CentreConfigUpdaterUtils.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/CriteriaResource.java
> Issue #1212

- platform-dao/src/main/java/ua/com/fielden/platform/entity/EntityExportActionDao.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/AbstractEntityEditActionProducer.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/AbstractEntityManipulationAction.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/EntityManipulationActionProducer.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/query/fluent/EntityQueryUtils.java
> Issue #1234

- platform-web-ui/src/main/java/ua/com/fielden/platform/web/action/post/GuardCentreRegenerationPostAction.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre-behavior.html
> Issue #1230

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-entity-grid-inspector.html
Introduced fix in equality method that handles the exception when key is not present.
> Fix for issue #1236

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-centre-result-view.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre-insertion-point.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-selection-view.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-bar-chart/tg-bar-chart.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-scrollable-component.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-security-matrix.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tree-table/tg-tree-table.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-entity-grid-inspector.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/tg-entity-master-styles.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/views/tg-menu-item-view.html
> Issue #1242

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-custom-action-dialog.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/tg-entity-master-behavior.html
> Issue #1247

- platform-dao/src/test/java/ua/com/fielden/platform/entity/meta/MetaPropertyCollectionalTest.java
- platform-dao/src/test/java/ua/com/fielden/platform/entity/meta/MetaPropertyFromPersistancePerspectiveTest.java
- platform-dao/src/test/java/ua/com/fielden/platform/entity/meta/MetaPropertyIdentificationOfRetrievablePropertiesTest.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/AbstractEntity.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/meta/MetaPropertyFull.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/entity/AbstractEntityTest.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/entity/Entity.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/entity/meta/MetaPropertyTest.java
> Issue #1250

- platform-dao/src/main/java/ua/com/fielden/platform/companion/PersistentEntitySaver.java
- platform-dao/src/main/java/ua/com/fielden/platform/test/DbCreator.java
- platform-dao/src/test/java/ua/com/fielden/platform/entity/SettingAndSavingActivatableEntitiesTest.java
> Issue #1252

- platform-dao/src/main/java/ua/com/fielden/platform/companion/PersistentEntitySaver.java
- platform-dao/src/test/java/ua/com/fielden/platform/entity/SettingAndSavingActivatableEntitiesTest.java
> Issue #1256

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-menu-search-input.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-collectional-editor.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-collectional-representor.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-colour-picker.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-datetime-picker.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-decimal-editor.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-entity-editor.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-hyperlink-editor.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-integer-editor.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-money-editor.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-singleline-text-editor.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/login-complete-reset.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/login-initiate-reset.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/login.html
> Issue #1276

- platform-dao/src/main/java/ua/com/fielden/platform/companion/PersistentEntitySaver.java
- platform-dao/src/main/java/ua/com/fielden/platform/utils/DbUtils.java
- platform-dao/src/test/java/ua/com/fielden/platform/dao/CommonEntityDaoTest.java
- platform-dao/src/test/java/ua/com/fielden/platform/dao/IdAssignmentWhenSavingEntitiesTest.java
- platform-dao/src/test/java/ua/com/fielden/platform/entity/ActivatableEntitiesWithSkipActivatableTrackingTest.java
- platform-dao/src/test/java/ua/com/fielden/platform/persistence/types/EntityWithMoney.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/RestServerUtil.java
> Issue #1290

- platform-web-resources/src/main/java/ua/com/fielden/platform/web/factories/webui/LogoutResourceFactory.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/LogoutResource.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/security/AbstractWebResourceGuard.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/test/server/TgTestApplicationConfiguration.java
- platform-web-resources/src/test/java/ua/com/fielden/web/domain_driven/authetication/WebResourceGuardTestCase.java
> Issue #1302

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre-insertion-point.html
> Issue #1311

- platform-dao/src/main/java/ua/com/fielden/platform/entity/query/generation/elements/EntProp.java
- platform-dao/src/main/java/ua/com/fielden/platform/entity/query/generation/elements/EntQuery.java
- platform-dao/src/test/java/ua/com/fielden/platform/entity/query/QueryModelCompositionTest.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/reflection/Reflector.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/reflection/asm/impl/DynamicEntityTypeGenerationTest.java
> Issue #1315

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-collectional-editor.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-editor.html
> Issue #1278

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/ioc/ObservableMutatorInterceptor.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/meta/MetaPropertyFull.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/entity/meta/PropertyDependencyHandlingTest.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/entity/meta/test_entities/EntityWithCircularDependentPropertiesAndDefiners.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/entity/meta/test_entities/definers/EntityWithCircularDependentPropertiesAndDefiners_PropOne_Definer.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/entity/meta/test_entities/definers/EntityWithCircularDependentPropertiesAndDefiners_PropTwoAndThree_Definer.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/entity/meta/test_entities/validators/EntityWithCircularDependentPropertiesAndDefiners_PropTree_Validator.java
> Issue #1324

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-entity-grid-inspector.js
> Issue #1322

- platform-dao/src/main/java/ua/com/fielden/platform/migration/DataMigrator.java
- platform-dao/src/main/java/ua/com/fielden/platform/migration/MigrateDb.java
- platform-dao/src/main/java/ua/com/fielden/platform/migration/RetrieverSqlProducer.java
> Issue #1319

- platform-web-resources/pom.xml
> #1326 Update Jetty version.

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-custom-action-dialog.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/menu/tg-master-menu.html
> Issue #1330

- platform-dao/src/main/java/ua/com/fielden/platform/security/session/UserSessionDao.java
- platform-dao/src/test/java/ua/com/fielden/platform/security/authentication/UserSessionCacheEvictionStrategyTestCase.java
- platform-dao/src/test/java/ua/com/fielden/platform/security/authentication/UserSessionFraudulentAuthenticationAttemptsTestCase.java
- platform-dao/src/test/java/ua/com/fielden/platform/security/authentication/UserSessionRecognisingStolenAndResuedAuthenticatorTestCase.java
- platform-dao/src/test/java/ua/com/fielden/platform/security/authentication/UserSessionValidationAndReestablishmentTestCase.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/security/session/IUserSession.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/utils/CollectionUtil.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/application/AbstractWebUiResources.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/application/ResourceRouter.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/FileProcessingResource.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/security/AbstractWebResourceGuard.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/sse/IEventSource.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/sse/SseUtils.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/sse/exceptions/InvalidSseUriException.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/sse/resources/EventSourcingResourceFactory.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/test/server/TgMachineRealtimeMonitorWebUiConfig.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/test/server/WebUiConfig.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/test/server/WebUiResources.java
- platform-web-resources/src/test/java/ua/com/fielden/web/domain_driven/authetication/WebResourceGuardTestCase.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-menu-search-example.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/file_operations/tg-file-processing-behavior.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/sse/sse.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/sse/tg-sse-behavior.html
> Issue #1336

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-egi-cell.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-entity-grid-inspector.js
> Issue #1342

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-collectional-editor.html
> Issue #1352

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-selection-view.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/chart-decker/tg-chart-decker-template.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-entity-grid-inspector.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/tg-entity-master-template-behavior.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/tg-entity-master-template.js
> Issue #1348

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/tg-entity-master.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/views/tg-app-menu.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/views/tg-app-view.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/views/tg-menu-item-view.js
> Issue #1357

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-entity-grid-inspector.js
> Issue #1347

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-multiline-text-editor.js
> Issue #1344

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-entity-grid-inspector.js
> Issue 1363

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-custom-action-dialog.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-entity-grid-inspector.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/index.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/menu/tg-master-menu.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/tg-entity-master.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/reflection/tg-polymer-utils.js
> Issue #1329

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-entity-editor-result.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-entity-editor.js
> Issue #1376

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre-behavior.js
> #1376 Implemented active autocompletion searches upon RUN and VIEW.

- platform-dao/src/main/java/ua/com/fielden/platform/entity/query/EntityContainerEnhancer.java
- platform-dao/src/main/java/ua/com/fielden/platform/entity/query/EntityContainerFetcher.java
- platform-dao/src/main/java/ua/com/fielden/platform/entity/query/EntityHibernateDeletionQueryProducer.java
- platform-dao/src/main/java/ua/com/fielden/platform/entity/query/EntityHibernateRetrievalQueryProducer.java
- platform-dao/src/main/java/ua/com/fielden/platform/entity/query/generation/elements/EntQuery.java
- platform-dao/src/main/java/ua/com/fielden/platform/entity/query/metadata/PropertyMetadata.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/criteria/generator/impl/CriteriaGenerator.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/domaintree/impl/DomainTreeEnhancer.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/domaintree/impl/DomainTreeEnhancer0.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/reflection/asm/impl/AdvancedAddClassAnnotationAdapter.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/reflection/asm/impl/AdvancedAddPropertyAdapter.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/reflection/asm/impl/AdvancedModifyPropertyAdapter.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/reflection/asm/impl/AdvancedRecordOriginalTypeAdapter.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/reflection/asm/impl/DynamicEntityClassLoader.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/reflection/asm/impl/DynamicTypeNamingService.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/reflection/asm/impl/TypeMaker.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/report/query/generation/AnalysisResultClass.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/serialisation/jackson/entities/FactoryForTestingEntities.java
- platform-pojo-bl/src/test/java/fielden/stresstests/GetOriginalTypeStressTest.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/entity/ChildEntity.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/reflection/PropertyTypeDeterminatorCheckingEnhancementsTest.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/reflection/asm/impl/DynamicEntityTypeGenerationTest.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/reflection/asm/impl/DynamicEntityTypeMixedAndRepetitiveModificationTest.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/reflection/asm/impl/DynamicEntityTypeModificationTest.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/reflection/asm/impl/DynamicModificationOfEntityTypesWithCircularDependencyTest.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/SerialisationTestResource.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/app/SerialisationTypeEncoder.java
> Issue #1381

- platform-dao/pom.xml
- platform-dao/src/main/java/ua/com/fielden/platform/ioc/session/SessionInterceptor.java
- platform-pojo-bl/pom.xml
> Issue #1392

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-entity-editor-result.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-entity-editor.js
> Issue #1391

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-entity-editor-result.js
> #1391 Fixed single selection when tapping on item other than first.

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-bar-chart/d3-bar-chart.js
> Issue #1402

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/app/tg-app-template.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/index.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/views/tg-app-menu.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/views/tg-app-view.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/views/tg-view-with-menu.js
> Issue #1388

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/validation/ActivePropertyValidator.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/validation/EntityExistsValidator.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/validation/custom/DomainEntitiesDependenciesUtils.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/validation/custom/DomainEntityDependencies.java
> Issue #1409

- platform-dao/src/main/java/ua/com/fielden/platform/companion/PersistentEntitySaver.java
- platform-dao/src/main/java/ua/com/fielden/platform/security/user/UserDao.java
- platform-dao/src/test/java/ua/com/fielden/platform/user/UserTestCase.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/validation/GreaterValidator.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/UserWebUiConfig.java
> Issue #1389

- platform-dao/src/main/java/ua/com/fielden/platform/sample/domain/TgPersistentEntityWithPropertiesDao.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/binding/tg-entity-binder-behavior.js
> Issue #1421

- platform-dao/src/main/java/ua/com/fielden/platform/entity/query/metadata/DomainMetadata.java
- platform-dao/src/test/java/ua/com/fielden/platform/entity/query/fetching/EntityQueryExecutionTest.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/TgBogie.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/TgBogieLocation.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/TgWagonSlot.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/TgWorkshop.java
> Issue #1193

- platform-dao/src/main/java/ua/com/fielden/platform/migration/AbstractRetrieverBatchStmtGenerator.java
> Issue #1446

- platform-dao/src/main/java/ua/com/fielden/platform/companion/AbstractEntityReader.java
- platform-dao/src/main/java/ua/com/fielden/platform/security/user/UserDao.java
- platform-dao/src/test/java/ua/com/fielden/platform/dao/CommonEntityDaoTest.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/AbstractEntity.java
> Issue #1456

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/annotation/IsProperty.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/annotation/factory/IsPropertyAnnotation.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/TgPersistentEntityWithProperties.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/serialisation/jackson/DefaultValueContract.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/serialisation/jackson/EntitySerialiser.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/serialisation/jackson/EntityTypeProp.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/web/test/config/ApplicationDomain.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/test/tg-entity-formatter.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-entity-editor.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-entity-formatter.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/reflection/tg-polymer-utils.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/reflection/tg-reflector.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/tests.html
> Issue #1175

- platform-dao/src/test/java/ua/com/fielden/platform/attachment/AttachmentOperationsTest.java
- platform-dao/src/test/java/ua/com/fielden/platform/test_config/AbstractDaoTestCase.java
> Issue #1460

- platform-dao/src/main/java/ua/com/fielden/platform/companion/PersistentEntitySaver.java
- platform-dao/src/test/java/ua/com/fielden/platform/dao/CommonEntityDaoTest.java
> Issue #1462

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/index.html
> Issue #1471

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-centre-result-view.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre-behavior.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-entity-grid-inspector.js
> Issue #1474

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-month-selector.js
> Issue #1469

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-tree.js
> Issue #1479

- platform-dao/src/main/java/ua/com/fielden/platform/persistence/types/SecurityTokenType.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/security/tokens/Template.java
> Issue #1478

- platform-web-ui/src/main/java/ua/com/fielden/platform/web/view/master/chart/decker/api/impl/ChartDeckerMaster.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/chart-decker/tg-chart-decker-template-behavior.js
> Issue #1496

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-entity-grid-inspector.js
> Issue #1501

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/ActivatableAbstractEntity.java
> Issue #1481

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-bar-chart/d3-bar-chart.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-bar-chart/tg-bar-chart.js
> Issue #1506

- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/CriteriaResource.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/IDynamicColumnConfig.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/impl/DynamicColumnBuilder.java
> Issue #1509

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-egi-master-behavior.js
> Issue #1498

- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/EgiConfigurations.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/EntityCentre.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/EntityCentreConfig.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/crit/layout/ILayoutConfigWithResultsetSupport.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/impl/EntityCentreBuilder.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/impl/ResultSetBuilder.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/impl/ResultSetBuilderWrapperForEditors.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/impl/SelectionCriteriaLayoutBuilder.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/insertion_points/IInsertionPoints.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/insertion_points/IInsertionPointsFlexible.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/insertion_points/InsertionPointBuilder.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/insertion_points/InsertionPointConfig.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/resultset/IResultSetBuilder0HideEgi.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/actions/tg-shortcut-processing-behavior.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre-behavior.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre-insertion-point.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre-styles.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre-template.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-tree.js
> Issue #1503

- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/CriteriaResource.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/EntityValidationResource.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/binding/tg-entity-binder-behavior.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/reflection/tg-reflector.js
> Issue #1513

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/criteria/generator/ICriteriaGenerator.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/criteria/generator/impl/CriteriaGenerator.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/application/AbstractWebUiResources.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/factories/webui/AppIndexResourceFactory.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/AbstractWebUiConfig.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/AppIndexResource.java
> Issue #1430

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/validation/GreaterOrEqualValidator.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/entity/validation/GreaterEqualAndMaxPropertyValidatorTest.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/entity/validation/test_entities/EntityWithGreaterOrEqualValidation.java
> Issue #1518

- platform-dao/src/main/java/ua/com/fielden/platform/ui/config/controller/EntityCentreConfigDao.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/ui/config/api/IEntityCentreConfig.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/CentreUpdater.java
> Issue #1522

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/test/tg-entity-master.html
> #1473 Fixed web test checking validation message for MaxValueValidator.

- platform-dao/src/main/java/ua/com/fielden/platform/companion/AbstractEntityReader.java
- platform-dao/src/test/java/ua/com/fielden/platform/dao/CommonEntityDaoTest.java
> #1530 Implemented required changes + improvements to test coverage.

- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/impl/EntityCentreBuilder.java
> Issue #1537

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/criteria/generator/impl/CriteriaGenerator.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/criteria/generator/impl/CriteriaGeneratorException.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/annotation/factory/DateAnnotations.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/crit_gen/TopLevelEntity.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/criteria/generator/impl/CriteriaGeneratorTest.java
> Issue #1044 fix date criteria

- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/impl/ResultSetBuilder.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/exceptions/EntityCentreConfigurationException.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/view/master/exceptions/EntityCentreConfigurationException.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/view/master/exceptions/EntityMasterConfigurationException.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-entity-editor.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-egi-master-behavior.js
> Issue #1556

- platform-dao/src/main/java/ua/com/fielden/platform/companion/helper/KeyConditionBuilder.java
- platform-dao/src/test/java/ua/com/fielden/platform/dao/CommonEntityDaoTest.java
- platform-dao/src/test/java/ua/com/fielden/platform/dao/EntityWithDynamicCompositeKeyDao.java
- platform-dao/src/test/java/ua/com/fielden/platform/dao/EntityWithSingleMemberDynamicCompositeKeyDao.java
- platform-dao/src/test/java/ua/com/fielden/platform/persistence/composite/EntityWithDynamicCompositeKey.java
- platform-dao/src/test/java/ua/com/fielden/platform/persistence/composite/EntityWithSingleMemberDynamicCompositeKey.java
- platform-dao/src/test/java/ua/com/fielden/platform/test/PlatformTestDomainTypes.java
> Issue #1516

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/binding/tg-entity-binder-behavior.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/test/tg-entity-centre.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/test/tg-entity-master.html
> Issue #1564

- platform-web-ui/src/main/java/ua/com/fielden/platform/web/action/post/FileSaverPostAction.java
> #1567 Implemented required changes.

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre-behavior.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-custom-action-dialog.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/tg-entity-master-behavior.js
> Issue #1570

- platform-web-ui/src/main/java/ua/com/fielden/platform/web/action/post/GuardCentreRegenerationPostAction.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-custom-action-dialog.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/reflection/tg-polymer-utils.js
> Issue #1582

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-entity-grid-inspector.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/reflection/tg-ajax-utils.js
> Issue #1563

- dev-misc/maven/settings.xml
> #1437 Updated central repo URIs.

- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/EntityCentre.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/EntityCentreConfig.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/impl/EntityCentreBuilder.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/impl/GenericCentreConfigBuilder.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/impl/ResultSetBuilder.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/impl/SelectionCriteriaLayoutBuilder.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/impl/TopLevelActionsBuilder.java
- platform-web-ui/src/test/java/ua/com/fielden/platform/web/centre/api/impl/EntityCentreBuilderResultSetTest.java
- platform-web-ui/src/test/java/ua/com/fielden/platform/web/centre/api/impl/EntityCentreBuilderSelectionCritTest.java
> Issue #1592

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/utils/EntityUtils.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/utils/EntityUtilsTest.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/criterion/tg-abstract-criterion-behavior.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre-template-behavior.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-toast.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-datetime-picker.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-multiline-text-editor.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-custom-action-dialog.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-entity-grid-inspector.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/tg-entity-master-behavior.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/reflection/tg-polymer-utils.js
> Issue #1595

- platform-dao/src/main/java/ua/com/fielden/platform/entity/EntityExportActionDao.java
- platform-dao/src/main/java/ua/com/fielden/platform/sample/domain/ExportActionDao.java
- platform-pojo-bl/pom.xml
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/file_reports/WorkbookExporter.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/file_reports/WorkbookExporterTest.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/CentreResourceUtils.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/file_operations/tg-file-processing-behavior.js
> Issue #846

- platform-dao/pom.xml
- platform-dao/src/main/java/ua/com/fielden/platform/ioc/HibernateConfigurationFactory.java
> Issue #1597

- platform-dao/src/main/java/ua/com/fielden/platform/security/session/UserSessionDao.java
- platform-dao/src/test/java/ua/com/fielden/platform/security/authentication/UserSessionCacheEvictionStrategyTestCase.java
- platform-dao/src/test/java/ua/com/fielden/platform/security/authentication/UserSessionRecognisingStolenAndResuedAuthenticatorTestCase.java
- platform-dao/src/test/java/ua/com/fielden/platform/security/authentication/UserSessionValidationAndReestablishmentTestCase.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/cypher/SessionIdentifierGenerator.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/security/session/Authenticator.java
- platform-web-resources/src/test/java/ua/com/fielden/web/domain_driven/authetication/WebResourceGuardTestCase.java
> Issue #1604

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/actions/tg-ui-action.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/binding/tg-entity-binder-behavior.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-confirmation-dialog.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-global-error-handler.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-toast.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/element_loader/tg-element-loader.js
> Issue #1606

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/DefaultEntityProducerWithContext.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/serialisation/jackson/EntitySerialiser.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/serialisation/jackson/EntityType.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/web/utils/EntityResourceUtils.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/app/tg-app-template.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-custom-action-dialog.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/menu/tg-master-menu.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/reflection/test/tg-reflector.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/reflection/tg-reflector.js
> Issue #1574 support for sharing of concrete menu item in compound masters + additional enhancements

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/domain/PlatformDomainTypes.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/menu/Action.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/menu/Menu.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/AbstractWebUiConfig.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/resultset/impl/FunctionalActionElement.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/menu/impl/MainMenuBuilder.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/menu/impl/WebMainMenu.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/view/master/api/actions/IAction.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/view/master/api/actions/post/IPostAction.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/view/master/api/actions/pre/IPreAction.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/app/tg-app-template.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-entity-editor-result.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-entity-editor.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-entity-grid-inspector.js
> Issue #1612

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-boolean-editor.js
> Issue #1618

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/EntityManipulationActionProducer.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/master/MasterInfo.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/view/master/MasterInfoProvider.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/actions/tg-ui-action.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre-template-behavior.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre-template.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-entity-grid-inspector.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-property-column.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/reflection/tg-polymer-utils.js
> Issue #1617

- platform-dao/src/main/java/ua/com/fielden/platform/sample/domain/TgDateTestEntityDao.java
- platform-dao/src/test/java/ua/com/fielden/platform/test/PlatformTestDomainTypes.java
- platform-dao/src/test/java/ua/com/fielden/platform/test/ioc/PlatformTestServerModule.java
- platform-dao/src/test/java/ua/com/fielden/platform/validators/OverlappingDateOnlyTest.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/ITgDateTestEntity.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/TgDateTestEntity.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/utils/EntityUtils.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/utils/Validators.java
> Issue #1629

- platform-dao/src/main/java/ua/com/fielden/platform/entity/query/generation/elements/DateOf.java
> #1636 Implemented casting of the second argument in DATE_TRUNC

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/tg-entity-master-behavior.js
> Issue #1627

- platform-web-resources/pom.xml
> #1646 Upgraded Jetty and Restlet.

- platform-dao/src/main/java/ua/com/fielden/platform/web_api/GraphQLService.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/domaintree/impl/AbstractDomainTreeRepresentation.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/utils/EntityUtils.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/utils/EntityUtilsTest.java
> Issue #1649

- platform-dao/src/main/java/ua/com/fielden/platform/mail/SmtpEmailSender.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/LoginResource.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-domain-explorer.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-tree-list-behavior.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-tree.js
> Issue #1670

- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/MenuWebUiConfig.java
> Issue #1685

- platform-pojo-bl/pom.xml
- platform-web-resources/pom.xml
> Issue #1667

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/tg-entity-master-behavior.js
> Issue #985

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-entity-editor.js
> Issue #1521

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/web/centre/CentreConfigDuplicateActionProducer.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/web/centre/CentreConfigEditActionProducer.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/web/centre/CentreConfigSaveActionProducer.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/resultset/impl/FunctionalActionElement.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/view/master/api/with_centre/impl/MasterWithCentre.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre-behavior.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre-insertion-point.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-selection-criteria-behavior.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/views/tg-view-with-menu.js
> Issue #1695

- platform-dao/src/test/java/ua/com/fielden/platform/dao/CommonEntityDaoTest.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/query/fluent/ValuePreprocessor.java
> #1699 Implemented issue requirements.

- platform-dao/pom.xml
- platform-pojo-bl/pom.xml
> #1694 Upgraded dependencies.

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/menu/Menu.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/menu/Module.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/menu/impl/MainMenuBuilder.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/menu/impl/WebMainMenu.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/menu/module/impl/WebMenuModule.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/app/tg-app-template.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/views/tg-app-menu.js
> Issue #1704

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/annotation/IsProperty.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/meta/MetaProperty.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/meta/MetaPropertyFull.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/validation/MaxLengthValidator.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/entity/validation/MaxLengthValidatorTest.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/entity/validation/test_entities/EntityWithMaxLengthValidation.java
> Issue #1709

- platform-web-ui/src/main/resources/polymer/@polymer/paper-checkbox/paper-checkbox.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-boolean-editor.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-collectional-editor.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-editor.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-entity-editor.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-egi-master-behavior.js
> Issues #1703, #1706

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/security/user/impl/DefaultAuthenticationModel.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/test/server/TgTestAppAuthenticationModel.java
> #1715 Implemented issue requirements.

- platform-doc/eclipse-templates/tg-templates.xml
> Issue #1718

- platform-dao/src/main/java/ua/com/fielden/platform/security/session/UserSessionDao.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/fetch/FetchModelReconstructor.java
> Milestone v1.4.5 m13

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/domaintree/centre/impl/CentreDomainTreeRepresentation.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/EntityCentre.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/reflection/tg-reflector.js
> Issue #1741

- platform-dao/src/main/java/ua/com/fielden/platform/eql/meta/EqlDomainMetadata.java
- platform-dao/src/main/java/ua/com/fielden/platform/sample/domain/TgUnionCommonTypeDao.java
- platform-dao/src/main/java/ua/com/fielden/platform/sample/domain/TgUnionDao.java
- platform-dao/src/main/java/ua/com/fielden/platform/sample/domain/TgUnionHolderDao.java
- platform-dao/src/main/java/ua/com/fielden/platform/sample/domain/TgUnionType1Dao.java
- platform-dao/src/main/java/ua/com/fielden/platform/sample/domain/TgUnionType2Dao.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/AbstractEntity.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/AbstractUnionEntity.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/fetch/FetchProvider.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/reflection/Finder.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/TgUnion.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/TgUnionCo.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/TgUnionCommonType.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/TgUnionCommonTypeCo.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/TgUnionHolder.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/TgUnionHolderCo.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/TgUnionType1.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/TgUnionType1Co.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/TgUnionType2.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/TgUnionType2Co.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/serialisation/jackson/EntitySerialiser.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/serialisation/jackson/EntityType.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/utils/DefinersExecutor.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/web/test/config/ApplicationDomain.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/entity/fetch/FetchProviderTest.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-egi-data-retrieval-behavior.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/reflection/test/tg-reflector.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/reflection/tg-reflector.js
> Issues #1557 #1558

- platform-web-ui/src/main/java/ua/com/fielden/platform/web/ref_hierarchy/ReferenceHierarchyProducer.java
> #1747 Ensured the use of the refetched entity instance.

- platform-web-ui/src/main/java/ua/com/fielden/platform/web/view/master/api/helpers/IWidgetSelector.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/view/master/api/helpers/impl/WidgetSelector.java
> #1752 Introduced widget selector asInteger and deprecated asSpinner.

- platform-web-resources/src/main/java/ua/com/fielden/platform/web/factories/webui/FileProcessingResourceFactory.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/FileProcessingResource.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-entity-grid-inspector.js
refs #1751 (please do not remove branch yet)
> Issue #1751

- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/FileProcessingResource.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/binding/tg-entity-binder-behavior.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-message-panel.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/file_operations/tg-attachment-uploader-list.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/file_operations/tg-attachment-uploader.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/file_operations/tg-file-processing-behavior.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/sse/tg-sse-behavior.js
> Issue #1756

- platform-dao/src/main/java/ua/com/fielden/platform/companion/PersistentEntitySaver.java
- platform-dao/src/test/java/ua/com/fielden/platform/entity/activatable/ActivatableEntitiesWithSkipActivatableTrackingTest.java
- platform-dao/src/test/java/ua/com/fielden/platform/entity/activatable/HandlingOfDeactivatableDependenciesTest.java
- platform-dao/src/test/java/ua/com/fielden/platform/entity/activatable/SavingNewActivatableEntitiesWithReferencesToOtherActivatablesTest.java
- platform-dao/src/test/java/ua/com/fielden/platform/entity/activatable/SavingNewActivatableEntitiesWithoutReferencesToOtherActivatablesTest.java
- platform-dao/src/test/java/ua/com/fielden/platform/entity/activatable/SettingAndSavingActivatableEntitiesTest.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/factory/ICompanionObjectFinder.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/validation/ActivePropertyValidator.java
> Issue #1766

- platform-dao/src/main/java/ua/com/fielden/platform/keygen/KeyNumberDao.java
- platform-dao/src/test/java/ua/com/fielden/platform/keygen/KeyNumberTest.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/keygen/IKeyNumber.java
> #1774 Implemented the core issue requiremetns + tests.

- platform-dao/src/main/java/ua/com/fielden/platform/entity/EntityExportActionDao.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity_centre/review/criteria/EntityQueryCriteria.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/ioc/IBasicWebApplicationServerModule.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/CentreResourceUtils.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/CriteriaResource.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/utils/CriteriaEntityRestorer.java
> Issue #1788

- platform-dao/src/main/java/ua/com/fielden/platform/attachment/AttachmentDao.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/attachment/Attachment.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/EntityAutocompletionResource.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/binding/tg-entity-binder-behavior.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-entity-editor.js
> Issue #1770

- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/EntityCentre.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/EntityCentreConfig.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/impl/ResultSetBuilder.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/impl/ResultSetDynamicPropertyBuilder.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/impl/TopLevelActionsBuilder.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/resultset/IResultSetBuilderDynamicProps.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/resultset/IResultSetBuilderDynamicPropsAction.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/resultset/impl/PropertyColumnElement.java
- platform-web-ui/src/test/java/ua/com/fielden/platform/web/centre/api/impl/EntityCentreBuilderResultSetTest.java
> Issue #1796

- platform-web-resources/src/main/java/ua/com/fielden/platform/web/vulcanizer/VulcanizingUtility.java
> Issue #1801

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre-behavior.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-selection-criteria.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/views/tg-menu-item-view.js
> Issue #1806

- platform-dao/src/test/java/ua/com/fielden/platform/sample/domain/EntityThreeDao.java
- platform-dao/src/test/java/ua/com/fielden/platform/sample/domain/UnionEntityWithoutSecondDescTitleDao.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/EntityThree.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/EntityThreeCo.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/UnionEntityWithoutSecondDescTitle.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/UnionEntityWithoutSecondDescTitleCo.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/web/test/config/ApplicationDomain.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/reflection/test/tg-reflector.html
> Issue #1804

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-selection-criteria-behavior.js
> Issue  #1820

- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/resultset/impl/FunctionalActionElement.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/view/master/api/with_master/impl/EntityManipulationMaster.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/view/master/api/with_master/impl/MasterWithMaster.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/actions/tg-ui-action.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/tg-entity-master-behavior.js
> Issue #1821

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-editor.js
> Issue #1824

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre-insertion-point.js
> Issue #1836

- platform-web-resources/src/main/java/ua/com/fielden/platform/web/vulcanizer/VulcanizingUtility.java
> Issue #1838

- platform-annotation-processors/src/main/java/ua/com/fielden/platform/processors/metamodel/MetaModelProcessor.java
- platform-annotation-processors/src/main/java/ua/com/fielden/platform/processors/metamodel/utils/EntityFinder.java
- platform-annotation-processors/src/test/java/ua/com/fielden/platform/processors/metamodel/utils/EntityFinderTest.java
- platform-annotations/src/main/java/ua/com/fielden/platform/annotations/metamodel/WithMetaModel.java
> #1841 Implemented issue requirements.

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/validation/GreaterOrEqualValidator.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/validation/GreaterValidator.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/validation/MaxValueValidator.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/entity/validation/GreaterEqualAndMaxPropertyValidatorTest.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/entity/validation/test_entities/EntityWithGreaterAndMaxValidations.java
> #1843 Implemented issue requirements.

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre-template-behavior.js
> Issue #1852

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/security/annotations/SsoAuthority.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/security/annotations/SsoClientId.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/security/annotations/SsoKeystore.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/security/annotations/SsoKeystorePasswd.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/security/annotations/SsoRedirectUriSignIn.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/security/annotations/SsoRedirectUriSignOut.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/security/annotations/SsoStateHashingKey.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/factories/webui/LogoutResourceFactory.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/factories/webui/exceptions/LogoutResourceException.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/LogoutResource.java
> Issue #1862 (SLO)

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/file_operations/tg-attachment-uploader-list.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/file_operations/tg-file-processing-behavior.js
> #1823 File upload improvements.

- platform-web-resources/src/main/java/ua/com/fielden/platform/web/factories/webui/LogoutResourceFactory.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/LogoutResource.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/vulcanizer/VulcanizingUtility.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/service-worker.js
> Issue #1862

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/types/Money.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/types/MoneyTestCase.java
> #1653 Complete certainty of Money actual value

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre-behavior.js
> #1854 Corrected the reject call.

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/chart-decker/tg-chart-decker-template-behavior.js
> Issue #1873

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/security/provider/SecurityTokenNode.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/security/provider/SecurityTokenProvider.java
> Issue #1809

- platform-web-resources/pom.xml
> #1894 Upgraded to the latest 9.x version of Jetty.

- platform-pojo-bl/pom.xml
> #1896 Updated the Guava dependency.

- platform-pojo-bl/pom.xml
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/utils/JodaTimeZoneTest.java
> Issue #1917 – Upgrade Joda Time

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity_centre/review/criteria/EntityQueryCriteria.java
> Issue #1929 – RetrieveAll option on entity centre should not return summary object for empty resultset

- platform-dao/src/test/java/ua/com/fielden/platform/basic/autocompleter/FallbackValueMatcherWithContextTest.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/basic/ValueMatcherUtils.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/basic/autocompleter/AbstractSearchEntityByKeyWithCentreContext.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/basic/autocompleter/AbstractSearchEntityByKeyWithContext.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/EntityAutocompletionResource.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/test/tg-entity-centre-filtering.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-menu-list.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-tree-list-behavior.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-collectional-editor.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-entity-editor.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-highlighter.js
> Issue #1944 - Autocompleter: default entity matchers to respect wildcards when searching by desc

- platform-web-ui/src/main/java/ua/com/fielden/platform/web/security/SecurityMatrixInsertionPointMaster.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/view/master/api/widgets/impl/AbstractWidget.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/view/master/hierarchy/ReferenceHierarchyMaster.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/view/master/metadata/DomainExplorerInsertionPointMaster.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-boolean-editor.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-collectional-representor.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-decimal-editor.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-editor.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-entity-editor.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-integer-editor.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-money-editor.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-multiline-text-editor.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-numeric-editor.js
> Issue #1922 – Copy editor content as rendered

- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/EntityCentre.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-entity-editor-result.js
> Issue #1735 – Autocompleter: a visual cue for inactive values of activatable entities

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/TgPersistentCompositeEntity.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/test/tg-entity-editor.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-entity-editor.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/tests.html
> Issue #1965

- platform-benchmark/pom.xml
- platform-dao/pom.xml
- platform-dao/src/main/java/ua/com/fielden/platform/entity/EntityResourceContinuationsHelper.java
- platform-dao/src/main/java/ua/com/fielden/platform/entity/UserDefinableHelpDao.java
- platform-dao/src/main/java/ua/com/fielden/platform/ioc/BasicWebServerModule.java
- platform-pojo-bl/pom.xml
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/UserDefinableHelpCo.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/UserDefinableHelpProducer.java
- platform-web-resources/pom.xml
- platform-web-resources/src/main/resources/application.properties
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/test/tg-entity-master.html
> Issue #1960 - Default URI support

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-entity-editor-result.js
> Issue #1735 – autocompleter improvement to rendering of inactive values

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-entity-editor.js
> Issue #1967

- platform-dao/src/main/java/ua/com/fielden/platform/mail/SmtpEmailSender.java
> #1974 - SMTP sender to support custom port

- platform-dao/src/main/java/ua/com/fielden/platform/entity/UserDefinableHelpDao.java
> #1986 Adjusted the scope for token UserDefinableHelp_CanSave_Token.

- platform-dao/src/test/java/ua/com/fielden/platform/attachment/AttachmentBasicPropertiesTest.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/attachment/Attachment.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/attachment/definers/AssignAttachmentTitle.java
> Issue #1988

- platform-dao/src/main/java/ua/com/fielden/platform/attachment/AttachmentDao.java
- platform-dao/src/test/java/ua/com/fielden/platform/attachment/AttachmentBasicPropertiesTest.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/attachment/Attachment.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/attachment/definers/AssignAttachmentTitle.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/attachment/validators/AttachmentTitleValidator.java
> Issue #1988 - Attachments: sanitise values for title upon file upload + validation

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/reflection/tg-polymer-utils.js
> Issue #1997 - Relax `a` tag restriction in the confirmation dialog messages

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-collectional-representor.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-editor.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-entity-editor.js
> Issue-#2002 - Hide copy action on egi master editors

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-collectional-representor.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-editor.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-entity-editor.js
merged from Issue-#2002 branch
> Issue-#2002 (modern) - Hide copy action on egi master editors

- platform-pojo-bl/pom.xml
> #2017 Upgraded Guava dependency to 32.0.1-jre.

- platform-dao/src/main/java/ua/com/fielden/platform/sample/domain/compound/TgCompoundEntityDao.java
- platform-dao/src/main/java/ua/com/fielden/platform/sample/domain/compound/TgCompoundEntityDetailDao.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/compound/ui_actions/producers/OpenTgCompoundEntityMasterActionProducer.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/domaintree/impl/AbstractDomainTreeRepresentationAndEnhancerTest.java
- platform-web-resources/src/main/java/fielden/test_app/config/compound/TgCompoundEntityWebUiConfig.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/CentreResourceUtils.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/action/post/BindSavedPropertyPostActionSuccess.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/action/post/GuardCentreRegenerationPostAction.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/app/tg-app-template.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/binding/tg-entity-binder-behavior.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/test/tg-entity-centre-generation.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre-behavior.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-selection-criteria-behavior.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-month-selector.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-editor.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-entity-editor.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-custom-action-dialog.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-egi-master-behavior.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-entity-grid-inspector.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/gis/tg-gis-component.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/actions/tg-action.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/test/tg-compound-master.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/test/tg-entity-master.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/tg-entity-master-behavior.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/reflection/tg-reflector.js
> Issue #2005 - Compound Master: web tests

- platform-dao/src/main/java/ua/com/fielden/platform/sample/domain/compound/TgCompoundEntityDao.java
- platform-dao/src/main/java/ua/com/fielden/platform/sample/domain/compound/TgCompoundEntityDetailDao.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/compound/ui_actions/producers/OpenTgCompoundEntityMasterActionProducer.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/domaintree/impl/AbstractDomainTreeRepresentationAndEnhancerTest.java
- platform-web-resources/src/main/java/fielden/test_app/config/compound/TgCompoundEntityWebUiConfig.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/CentreResourceUtils.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/action/post/BindSavedPropertyPostActionSuccess.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/action/post/GuardCentreRegenerationPostAction.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/app/tg-app-template.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/binding/tg-entity-binder-behavior.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/test/tg-entity-centre-generation.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre-behavior.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-selection-criteria-behavior.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-month-selector.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-editor.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-entity-editor.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-custom-action-dialog.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-egi-master-behavior.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-entity-grid-inspector.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/gis/tg-gis-component.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/actions/tg-action.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/test/tg-compound-master.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/test/tg-entity-master.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/tg-entity-master-behavior.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/reflection/tg-reflector.js
> Issue #2005 - Compound Master: web tests (modern)

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/AbstractProducerForOpenEntityMasterAction.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/master/MasterInfo.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/view/master/MasterInfoProvider.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/actions/tg-ui-action.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/tg-entity-master-template.js
> Issue #2014 - Entity Master: title actions to support master entity in a context

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-egi-data-retrieval-behavior.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-entity-grid-inspector.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-property-column.js
> Issue #2013 - Missing property action for dynamic columns

- platform-web-ui/src/main/java/ua/com/fielden/platform/web/action/post/BindSavedPropertyPostActionSuccess.java
> Issue #2026 - BindSavedProperty post actions do not work

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/TgPersistentEntityWithProperties.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/test/server/BigDecimalPropActionSelector.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/test/server/PopulateDb.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/test/server/WebUiConfig.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/test/tg-entity-master.html
> Issue #2028 - BindSavedProperty post actions and Entity Master actions / multi-actions basic web tests

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/TgPersistentEntityWithProperties.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/test/server/BigDecimalPropActionSelector.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/test/server/PopulateDb.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/test/server/WebUiConfig.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/test/tg-entity-master.html
> Issue #2028 - BindSavedProperty post actions and Entity Master actions / multi-actions basic web tests (modern)

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre-template-behavior.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-custom-action-dialog.js
> Issue #2038 - Close dialog button gets propagated into the view behind the dialog

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/file_reports/WorkbookExporter.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/file_reports/WorkbookExporterTest.java
> #2042 Implemented issue requirements.

- platform-web-ui/src/main/java/ua/com/fielden/platform/web/action/CentreConfigurationWebUiConfig.java
> Issue #2049 (modern) - Make Customise Columns dialog with absolute dimensions

- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/insertion_points/InsertionPointBuilder.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre-insertion-point.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-custom-action-dialog.js
> Issue #2056 - Entity Master: miximise to 100%

- platform-dao/src/main/java/ua/com/fielden/platform/sample/domain/TgPersistentEntityWithPropertiesDao.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/actions/tg-action.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/tg-entity-master-behavior.js
> Issue #1953 - Dialogs for continuations upset progress indication

- platform-dao/src/main/java/ua/com/fielden/platform/sample/domain/TgPersistentEntityWithPropertiesDao.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/actions/tg-action.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/tg-entity-master-behavior.js
> Issue #1953 (modern) - Dialogs for continuations upset progress indication

- platform-dao/src/main/java/ua/com/fielden/platform/sample/domain/TgVehicleDao.java
- platform-dao/src/test/java/ua/com/fielden/platform/dao/CommonEntityDaoTest.java
- platform-dao/src/test/java/ua/com/fielden/platform/entity/fetch/FetchModelReconstructionTest.java
- platform-dao/src/test/java/ua/com/fielden/platform/entity/proxy/EntityProxyLoadingTest.java
- platform-dao/src/test/java/ua/com/fielden/platform/entity/query/fetching/EntityQueryExecutionTest.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/fetch/FetchModelReconstructor.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/TgVehicle.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/TgVehicleFinDetails.java
> Issue #2070

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/web/centre/AbstractCentreConfigCommitAction.java
> #2075 Implemented the core change.

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-custom-action-dialog.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/reflection/tg-polymer-utils.js
> Issue #2055 - Entity Master: persist dimensions and position (locally)

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-custom-action-dialog.js
> Issue #2084 - Dialogs without prefferred dimensions gets callapsed into point with 0x0 dimension

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/app/tg-app-template.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-entity-centre-insertion-point.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/centre/tg-insertion-point-manager.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-toast-behavior.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-custom-action-dialog.js
> Issue #2064 - Navigation back should close maximised Entity Masters and restore maximised Insertion Points

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-custom-action-dialog.js
> Issue #2089 - Collapse button on dialogs doesn't minimise it's content

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/test/tg-datetime-picker-approximations-for-DDMMYYYY-slash-24hours.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/test/tg-datetime-picker-approximations-for-MMDDYYYY-slash-12hours.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/test/tg-datetime-picker-time-zones.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-datetime-picker.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/reflection/tg-date-utils.js
> Issue #2093 - Dates: hours : minutes : seconds format

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/web/utils/EntityResourceUtils.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/test/tg-entity-master-conflict-resolution.html
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/tg-entity-master-behavior.js
> Issue #2096 - Compound Master: avoid opener custom producing logic after successful save in NEW case

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/menu/tg-master-menu.js
> Issue #2100 - Compound Entity Master: D'n'D non-menu items cause unexpected errors.

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-custom-action-dialog.js
> Issue #2106 - Spread out title actions in top right corner of the dialog

- platform-dao/src/main/java/ua/com/fielden/platform/eql/stage3/conditions/LikeTest3.java
- platform-dao/src/main/java/ua/com/fielden/platform/eql/stage3/operands/functions/AbstractFunction3.java
This is a partial merge of the issue.
> Issue #1661

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/web/utils/EntityResourceUtils.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/CentreResourceUtils.java
> Issue #2122 -- Unexpected validation errors for required untouched dependent properties

- platform-dao/src/main/java/ua/com/fielden/platform/entity/query/generation/AbstractTokensBuilder.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/query/fluent/ConditionalOperand.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/query/fluent/EntityQueryProgressiveInterfaces.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/query/fluent/Tokens.java
> #2125 - Collectional associations: support for composition of critConditions

- platform-dao/src/test/java/ua/com/fielden/platform/user/UserTestCase.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/security/user/User.java
> #2129 - Relax constraints for User.key

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-dropdown-switch.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/actions/tg-action.js
> Issue #2136 - Adjust paddings in drop down list of SAVE and CANCEL buttons

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/tg-entity-master-behavior.js
> Issue #2131 - Focus first input on compound master save

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-custom-action-dialog.js
> Issue #2143 - Heterogeneous master jumps when dimensions are default

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity_centre/review/DynamicQueryBuilder.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/entity_centre/review/DynamicQueryBuilderTest.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/entity_centre/review/EntityForQueryPropertyTesting.java
> Issue #2141 - Criteria for crit-only property with sub-model do not work in Entity Centres with totals (modern java only)

- platform-annotation-processors/pom.xml
- platform-annotations/pom.xml
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/AbstractEntity.java
- pom.xml
> Issue #2151- Decompose packaging of platform-annotation-processors

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/AbstractEntity.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/ui/config/EntityCentreConfigCo.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/CriteriaResource.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/CentreUpdater.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/CentreUpdaterUtils.java
> Issue #2159 - Entity Centre: self-concurrent auto-running for default configuration cause non-intrusive changes being lost

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-entity-editor.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/actions/tg-action.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/menu/tg-master-menu.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/tg-entity-master-behavior.js
> Issue #2164 - Autocompleter title NEW action does not insert value on SAVE&* actions unlike simple SAVE action

- platform-annotation-processors/src/main/java/ua/com/fielden/platform/processors/appdomain/RegisteredEntitiesCollector.java
- platform-annotation-processors/src/main/java/ua/com/fielden/platform/processors/metamodel/MetaModelProcessor.java
- platform-annotation-processors/src/main/java/ua/com/fielden/platform/processors/metamodel/utils/ElementFinder.java
- platform-annotation-processors/src/main/java/ua/com/fielden/platform/processors/metamodel/utils/EntityFinder.java
- platform-annotation-processors/src/test/java/ua/com/fielden/platform/processors/metamodel/MetaModelStructureTest.java
- platform-annotation-processors/src/test/java/ua/com/fielden/platform/processors/metamodel/utils/EntityFinderTest.java
- platform-annotation-processors/src/test/java/ua/com/fielden/platform/processors/metamodel/utils/MetaModelFinderTest.java
> Issue #2150 - Meta-model: support union and synthetic entities by default

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/compound/TgCompoundEntity.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/view/master/api/widgets/autocompleter/impl/EntityAutocompletionWidget.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-entity-editor.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/menu/tg-master-menu.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/master/tg-entity-master-behavior.js
> Issue #2174 - Prevent continuous snatch back of title action on SAVE&NEW action of simple master

- platform-dao/src/main/java/ua/com/fielden/platform/eql/stage1/queries/AbstractQuery1.java
- platform-dao/src/main/java/ua/com/fielden/platform/eql/stage2/KeyPropertyExtractor.java
- platform-dao/src/main/java/ua/com/fielden/platform/eql/stage2/operands/Prop2.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-entity-grid-inspector.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/reflection/tg-polymer-utils.js
> Issue #2176 - Entity Centre: open master action for properties of a union entity type

- platform-dao/src/test/java/ua/com/fielden/platform/entity/EntityExistsValidationTest.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/criteria/generator/ICriteriaGenerator.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/criteria/generator/impl/CriteriaGenerator.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/ui/menu/sample/MiTgSystem.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/criteria/generator/impl/CriteriaGeneratorTest.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/sample/domain/crit_gen/CriteriaGeneratorTestModule.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/sample/domain/crit_gen/MiTopLevelEntity.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/CentreResourceUtils.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/app/SerialisationTypeEncoder.java
> Issue #2187 - Entity Centre: concurrency improvement for named configurations

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/criteria/generator/ICriteriaGenerator.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/criteria/generator/impl/CriteriaGenerator.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/criteria/generator/impl/CriteriaGeneratorTest.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/AppIndexResource.java
> Issue #2193

- platform-dao/src/main/java/ua/com/fielden/platform/mail/ReadEmailsSpike.java
- platform-dao/src/main/java/ua/com/fielden/platform/mail/SmtpEmailSender.java
- platform-dao/src/test/java/ua/com/fielden/platform/mail/SmtpEmailSenderTest.java
> Issue #2124

- platform-pojo-bl/pom.xml
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/reflection/AnnotationReflector.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/reflection/Finder.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/reflection/Reflector.java
> Issue #2198 - Improvements to reflection caches

- platform-dao/src/main/java/ua/com/fielden/platform/companion/PersistentEntitySaver.java
- platform-dao/src/main/java/ua/com/fielden/platform/ui/config/EntityCentreConfigDao.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/criteria/generator/impl/CriteriaGenerator.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/dao/exceptions/EntityWasUpdatedOrDeletedConcurrently.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/reflection/asm/api/NewProperty.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/reflection/asm/impl/DynamicEntityClassLoader.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/reflection/asm/impl/TypeMaker.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/criteria/generator/impl/CriteriaGeneratorTest.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/reflection/asm/api/NewPropertyTest.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/reflection/asm/impl/DynamicEntityTypePropertiesAdditionTest.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/reflection/asm/impl/DynamicEntityTypePropertiesModificationTest.java
> Issue #2207 - Entity Centre: concurrency improvement for named configurations (take 2)

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/web/centre/CentreConfigUpdaterUtils.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/EntityCentre.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/EntityCentreConfig.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/impl/ResultSetBuilder.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/impl/TopLevelActionsBuilder.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/resultset/IResultSetBuilder2Properties.java
- platform-web-ui/src/test/java/ua/com/fielden/platform/web/centre/api/impl/EntityCentreBuilderResultSetTest.java
> Issue #2215 - Entity Centre: ability to add properties as excluded from resultset by default

- platform-dao/src/main/java/ua/com/fielden/platform/test/AbstractDomainDrivenTestCase.java
- platform-dao/src/main/java/ua/com/fielden/platform/utils/DbUtils.java
- platform-dao/src/test/java/ua/com/fielden/platform/domain/testing/DateCreationTest.java
> #2118 - Domain testing: support for a wider variety of date/time formats

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/functional/centre/CentreContextHolder.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/web/utils/EntityResourceUtils.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/CriteriaEntityAutocompletionResource.java
> Issue #2221 - Entity Centre autocompletion: error autocompleting single-valued autotocompleter on centre without summary props

- platform-dao/src/main/java/ua/com/fielden/platform/companion/PersistentEntitySaver.java
- platform-dao/src/main/java/ua/com/fielden/platform/dao/CommonEntityDao.java
- platform-dao/src/test/java/ua/com/fielden/platform/dao/CommonEntityDaoStreamingTestCase.java
- platform-dao/src/test/java/ua/com/fielden/platform/dao/CommonEntityDaoTest.java
- platform-dao/src/test/java/ua/com/fielden/platform/dao/EntityWithMoneyDao.java
- platform-dao/src/test/java/ua/com/fielden/platform/dao/IEntityWithMoney.java
> Issue #2229 - Companion: improving error reporting for attempts at using non-existing or closed sessions

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/utils/CollectionUtil.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/utils/CollectionUtilTest.java
> CollectionUtil: a function to merge maps

- platform-dao/src/main/java/ua/com/fielden/platform/companion/DeleteOperations.java
- platform-dao/src/main/java/ua/com/fielden/platform/entity/query/EntityBatchDeleteByIdsOperation.java
- platform-dao/src/main/java/ua/com/fielden/platform/entity/query/EntityBatchDeleteByQueryModelOperation.java
- platform-dao/src/main/java/ua/com/fielden/platform/ui/config/EntityCentreConfigDao.java
- platform-dao/src/main/java/ua/com/fielden/platform/ui/config/MainMenuItemDao.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/dao/exceptions/EntityDeletionException.java
> Entity deletion: improve exception handling

- platform-dao/src/main/java/ua/com/fielden/platform/dao/CommonEntityDao.java
- platform-dao/src/main/java/ua/com/fielden/platform/entity/EntityResourceContinuationsHelper.java
- platform-dao/src/main/java/ua/com/fielden/platform/ioc/session/SessionInterceptor.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/ioc/ObservableMutatorInterceptor.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/error/Result.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/reflection/Reflector.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/EntityCentre.java
> Issue #2253

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/layout/tg-flex-layout.js
> Issue #2252 - Layout: automatically expand sections containing properties with error, warning or informative message

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-boolean-editor.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-multiline-text-editor.js
> Issue #2257 - Multiline text editor has extra 2 pixel padding

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/file_operations/tg-file-processing-behavior.js
> Issue #2272 - File Processing: use custom error handler during initial phase of file opening

- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/CriteriaResource.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-custom-action-dialog.js
> Issue #2285 - Miscellaneous Web UI improvements

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/egi/tg-entity-grid-inspector.js
> Issue #2292 - Entity Centre: API for unselecting entities in a data page based on their IDs

- platform-web-resources/pom.xml
> #2332 Upgraded Jetty and Restlet.

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-tooltip.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/views/tg-app-menu.js
> Issue #2335 - Enhanced idea button tooltip  

- platform-dao/src/main/java/ua/com/fielden/platform/eql/retrieval/EntityContainerFetcher.java
- platform-dao/src/test/java/ua/com/fielden/platform/dao/CommonEntityDaoStreamingTestCase.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/streaming/SequentialGroupingStream.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/streaming/SequentialGroupingStreamExampleTestCase.java
> #2344 Removed SequentialGroupingStream#streamClosedOnTermination

- platform-annotation-processors/pom.xml
- platform-annotations/pom.xml
- platform-benchmark/pom.xml
- platform-dao/pom.xml
- platform-dao/src/main/java/ua/com/fielden/platform/web_api/GraphQLService.java
- platform-dao/src/test/java/ua/com/fielden/platform/web_api/fields/WebApiEntityFieldTest.java
- platform-dao/src/test/java/ua/com/fielden/platform/web_api/fields/WebApiStringFieldTest.java
- platform-db-evolution/pom.xml
- platform-pojo-bl/pom.xml
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity_centre/review/DynamicQueryBuilder.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/web_api/FieldSchema.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/web_api/RootEntityUtils.java
- platform-web-resources/pom.xml
- platform-web-ui/pom.xml
- pom.xml
Resolve #2366
Some issue might be very descriptive and server in place of a wiki page.
> Issue #2366 - GraphQL: support for eq

- platform-dao/src/main/java/ua/com/fielden/platform/entity/query/EntityBatchInsertOperation.java
- platform-dao/src/main/java/ua/com/fielden/platform/eql/retrieval/EntityContainerFetcherImpl.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/streaming/SequentialGroupingStream.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/utils/StreamUtils.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/streaming/SequentialGroupingStreamExampleTestCase.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/streaming/SequentialGroupingStreamTestCase.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/utils/StreamUtilsTest.java
Resolve #2378.
Marked the task items in section "Significant changes" as completed to indicated that corresponding changes have been reviewed, improved if necessary, and approved.
> Refactor SequentialGroupingStream to address defects

- .github/pull_request_template.md
- platform-dao/src/main/java/ua/com/fielden/platform/security/user/UserDao.java
- platform-dao/src/test/java/ua/com/fielden/platform/user/UserInSsoModeTestCase.java
- platform-dao/src/test/java/ua/com/fielden/platform/user/UserTestCase.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/security/user/IUser.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/security/user/UserSecret.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/security/user/UserSecretCo.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/utils/DefaultDates.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/factories/webui/LogoutResourceFactory.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/LoginCompleteResetResource.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/LoginInitiateResetResource.java
Resolve #2384
There are 3 main changes:
1. Password reset UUID is now encoded in order to escape any characters in the user name, which might break the reset URL.
2. Finding matching user by UUID is now performed by UUID only, without the extra condition on the user name.
3. The expiration time for password reset UUIDs is calculated and validated using the server timezone.
This section should be completed with reference to section [Performing PR review](https://github.com/fieldenms/devops/wiki/Code-and-PR-reviews#performing-pr-review) of the …
> #2384 Improvements to password resetting in the RSO mode.

- platform-dao/src/main/java/ua/com/fielden/platform/entity/EntityExportActionDao.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/file_reports/WorkbookExporter.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/file_reports/WorkbookExporterTest.java
Resolve #2386
Marked the task items in section "Significant changes" as completed to indicated that corresponding changes have been reviewed, improved if necessary, and approved.
> Issue #2386 - Workbook Exporter: stream may be operated on more than once

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/domaintree/impl/CalculatedProperty.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/AbstractEntity.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/annotation/IsProperty.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/annotation/factory/ParamAnnotation.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/meta/MetaProperty.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/meta/MetaPropertyFull.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/validation/MaxLengthValidator.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/validation/SanitiseHtmlValidator.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/types/RichText.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/types/RichTextSanitiser.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/entity/before_change_event_handling/BeforeChangeTest.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/entity/meta/MetaPropertyTest.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/entity/validation/MaxLengthValidatorTest.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/entity/validation/RichTextValidatorTest.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/entity/validation/StringHtmlSanitisationTest.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/entity/validation/test_entities/EntityWithMaxLengthValidation.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/types/RichTextHtmlTest.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-editor.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-multiline-text-editor.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-singleline-text-editor.js
Resolve #2391 
Some issue might be very descriptive and server in place of a wiki page.
This issue introduced implicit validator `SanitiseHtmlValidator` for all `String`-typed properties. This change has performance implications, which depend on the length of the text being santitised, the number of properties being changed, and the number of instances being affected. Judging by the time increase for running unit tests, the performance hit is about `10%`, which is acceptable in …
> Issue #2391 - Default constraints for String properties: length and HTML sanitisation

- platform-web-ui/src/main/java/ua/com/fielden/platform/web/centre/api/resultset/toolbar/impl/CentreToolbar.java
Resolve #2399
Marked the task items in section "Significant changes" as completed to indicated that corresponding changes have been reviewed, improved if necessary, and approved.
> Issue #2399 - Correction of a spelling mistake in API method of the `CentreToolbar` class

- platform-dao/src/main/java/ua/com/fielden/platform/companion/PersistentEntitySaver.java
- platform-dao/src/test/java/ua/com/fielden/platform/entity/AutomaticConflictResolutionTest.java
- platform-dao/src/test/java/ua/com/fielden/platform/entity/meta/MetaPropertyIdentificationOfRetrievablePropertiesTest.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/annotation/MapTo.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/reflection/AnnotationReflector.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/TeVehicleMake.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/TgCategory.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/sample/domain/TgVehicleMake.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/reflection/AnnotationReflectorTest.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/reflection/test_entities/FirstLevelEntity.java
Resolve #2406
Some issue might be very descriptive and server in place of a wiki page.
Marked the task items in section "Significant changes" as completed to indicate that corresponding changes have been reviewed, …
> #2406 - Optimistic locking: optional automatic conflict resolution at the level of properties

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/types/RichTextSanitiser.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/types/RichTextHtmlSanitisationTest.java
Resolve #2425
Marked the task items in section "Significant changes" as completed to indicate that corresponding changes have been …
> Issue #2425 - HTML sanitisation to permit `<extended>` 

- .github/workflows/codeql.yml
- platform-dao/src/main/java/ua/com/fielden/platform/companion/PersistentEntitySaver.java
- platform-dao/src/test/java/ua/com/fielden/platform/entity/activatable/SavingNewActivatableEntitiesWithReferencesToOtherActivatablesTest.java
- platform-dao/src/test/java/ua/com/fielden/platform/entity/activatable/SettingAndSavingActivatableEntitiesTest.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/utils/MiscUtilities.java
Resolve #2416
Marked the task items in section "Significant changes" as completed to indicate that corresponding changes have been reviewed, improved if necessary, and approved.
> Issue #2416 - Activatable entity: concurrency edge-case permitting core invariant violation

- platform-benchmark/pom.xml
- platform-dao/pom.xml
- platform-db-evolution/pom.xml
- platform-web-resources/pom.xml
- pom.xml
Resolve #2423
One web test is failing, but that was the case before the changes. Please refer additional details.
@jhou-pro : it is successful, but requires a workaround to run.
The following web test is failing, but it was failing for me before the dependency updates. …
> Issue #2423 - Upgrade Jetty to 9.4.57.v20241219 and Restlet to 2.5.1

- platform-dao/src/main/java/ua/com/fielden/platform/eql/stage3/sundries/OrderBy3.java
- platform-dao/src/main/java/ua/com/fielden/platform/eql/stage3/sundries/OrderBys3.java
- platform-dao/src/test/java/ua/com/fielden/platform/entity/query/OrderByTest.java
> Issue #2429 - EQL: Deduplicate order-by lists

- platform-dao/src/main/java/ua/com/fielden/platform/migration/MigrationUtils.java
Resolve #2439
Marked the task items in section "Significant changes" as completed to indicate that corresponding changes have been …
> Issue #2439 - Regression in `MigrationUtils` due to metadata transition

- platform-web-ui/src/main/web/ua/com/fielden/platform/web/app/tg-app-template.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-link-opener.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/editors/tg-hyperlink-editor.js
> Issue #2438 - Confirm with users when opening hyperlinks to external resources

- platform-dao/src/main/java/ua/com/fielden/platform/keygen/KeyNumberDao.java
- platform-dao/src/main/java/ua/com/fielden/platform/security/session/UserSessionDao.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/keygen/KeyNumber.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/security/annotations/SsoStateCypherSalt.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/security/session/ISsoSessionController.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/factories/webui/LogoutResourceFactory.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/LogoutResource.java
Resolve #2451
These changes effect only application with SSO where the Identity Provider (IdP) supports front-channel logout that requires the `id_token_hint` parameter as part of the logout request.
This section should be completed with reference to section [Performing …
> Issue #2451 - Improved support for OpenID Connect Single Log-Out

- platform-dao/src/main/java/ua/com/fielden/platform/eql/antlr/ConditionVisitor.java
- platform-dao/src/test/java/ua/com/fielden/platform/dao/dynamic/DynamicQueryBuilderSqlTest.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity_centre/review/DynamicQueryBuilder.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/utils/CollectionUtil.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/utils/StreamUtils.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/utils/CollectionUtilTest.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/utils/StreamUtilsTest.java
> Issue #2462 - Collectional crit-condition with property `key`

- platform-dao/src/main/java/ua/com/fielden/platform/ioc/BasicWebServerIocModule.java
- platform-dao/src/test/java/ua/com/fielden/platform/menu/MenuProducerTest.java
- platform-pojo-bl/pom.xml
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/menu/Menu.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/menu/MenuProducer.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/menu/ModuleMenu.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/menu/exceptions/MenuInitialisationException.java
- platform-web-resources/src/main/java/ua/com/fielden/platform/web/resources/webui/AbstractWebUiConfig.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/app/IWebUiConfig.java
- platform-web-ui/src/main/java/ua/com/fielden/platform/web/app/config/WebUiBuilder.java
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/app/config/tg-app-config.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/app/tg-app-template.js
- platform-web-ui/src/main/web/ua/com/fielden/platform/web/components/tg-link-opener.js
> Issue #2461 - External sites allowlist: support updating the allowlist at the application property level

- platform-annotation-processors/src/main/java/ua/com/fielden/platform/processors/metamodel/MetaModelProcessor.java
- platform-annotation-processors/src/test/java/ua/com/fielden/platform/processors/metamodel/utils/MetaModelFinderTest.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/AbstractUnionEntity.java
> Issue #2456 - Meta-model for `AbstractUnionEntity`

- platform-dao/src/main/java/ua/com/fielden/platform/companion/PersistentEntitySaver.java
- platform-dao/src/test/java/ua/com/fielden/platform/entity/activatable/AbstractEntityActivatabilityTestCase.java
> Issue #2486 - Activatable Entity: edge-case in ref counting for dirty properties

- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/exceptions/InvalidArgumentException.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/entity/validation/RangeValidatorFunction.java
- platform-pojo-bl/src/main/java/ua/com/fielden/platform/utils/DateUtils.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/entity/validation/DateRangePropertyValidatorTest.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/entity/validation/test_entities/EntityWithRangeProperties.java
- platform-pojo-bl/src/test/java/ua/com/fielden/platform/utils/DateUtilsTest.java
> Issue #2493 - Support `@TimeOnly` and `@DateOnly` ranges

- platform-annotation-processors-test/pom.xml
- platform-annotation-processors-test/src/main/java/ua/com/fielden/platform/processors/test_entities/ExampleEntity.java
- platform-annotation-processors-test/src/main/java/ua/com/fielden/platform/processors/test_entities/PersistentEntity.java
- platform-annotation-processors-test/src/test/java/ua/com/fielden/platform/processors/metamodel/MetaModelStructureTest.java
- platform-annotation-processors-test/src/test/java/ua/com/fielden/platform/processors/metamodel/utils/EntityFinderTest.java
- platform-annotation-processors/src/main/java/ua/com/fielden/platform/processors/metamodel/MetaModelProcessor.java
- platform-annotation-processors/src/main/java/ua/com/fielden/platform/processors/metamodel/utils/ElementFinder.java
- platform-annotation-processors/src/main/java/ua/com/fielden/platform/processors/metamodel/utils/EntityFinder.java
Resolve #2525
fieldenms/ports#110 can be used to see the new meta-models in action.
This section should be completed with reference to section [Performing PR review](https://github.com/fieldenms/devops/wiki/Code-and-PR-reviews#performing-pr-review) of the [Code and PR …
> Issue #2525 - Enhance metamodel generation to include common properties for union entities
